#pragma once

#define BNOCONTROL_SENSOR_GRAVITY_VALUE						(0)

#define SENSOR_DATA_TYPE_COUNT			16
#define CUSTOM_SENSOR_DATA_TYPE_COUNT	50

#define SENSOR_DATA_TYPE_CALIBRATION_STATUS_SYSTEM			0
#define SENSOR_DATA_TYPE_CALIBRATION_STATUS_GYRO			1
#define SENSOR_DATA_TYPE_CALIBRATION_STATUS_ACC				2
#define SENSOR_DATA_TYPE_CALIBRATION_STATUS_MAG				3



#define SENSOR_DATA_TYPE_RELATIVE_ACCELERATION_NED_X		4
#define SENSOR_DATA_TYPE_RELATIVE_ACCELERATION_NED_Y		5
#define SENSOR_DATA_TYPE_RELATIVE_ACCELERATION_NED_Z		6

#define SENSOR_DATA_TYPE_RELATIVE_VELOCITY_NED_X			7
#define SENSOR_DATA_TYPE_RELATIVE_VELOCITY_NED_Y			8
#define SENSOR_DATA_TYPE_RELATIVE_VELOCITY_NED_Z			9

#define SENSOR_DATA_TYPE_RELATIVE_POSITION_NED_X			10
#define SENSOR_DATA_TYPE_RELATIVE_POSITION_NED_Y			11
#define SENSOR_DATA_TYPE_RELATIVE_POSITION_NED_Z			12


#define SENSOR_DATA_TYPE_DISTANCE_ACTION_0					13
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_1					14
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_2					15
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_3					16
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_4					17
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_5					18
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_6					19
#define SENSOR_DATA_TYPE_DISTANCE_ACTION_7					20

#define SENSOR_DATA_TYPE_ROLL_COMPANSED_QUATERNION_W		21
#define SENSOR_DATA_TYPE_ROLL_COMPANSED_QUATERNION_X		22
#define SENSOR_DATA_TYPE_ROLL_COMPANSED_QUATERNION_Y		23
#define SENSOR_DATA_TYPE_ROLL_COMPANSED_QUATERNION_Z		24

#define SENSOR_DATA_TYPE_FREE_SLOT							25
#define SENSOR_DATA_TYPE_ROLL_COMPANSED_RIGHT_ACC			26
#define SENSOR_DATA_TYPE_ROLL_AND_PITCH_COMPANSED_DOWN_ACC	27

#define SENSOR_DATA_TYPE_TIME_DIFF							28
#define SENSOR_DATA_TYPE_QUATERNION_DISTANCE_TO_REFERANCE	29

//#define SENSOR_DATA_TYPE_CALCULATED_PSI						30
//#define SENSOR_DATA_TYPE_CALCULATED_TILT					31
//#define SENSOR_DATA_TYPE_CALCULATED_PHI						32

#define SENSOR_DATA_TYPE_FILTERED_ACC_NED_X					30
#define SENSOR_DATA_TYPE_FILTERED_ACC_NED_Y					31
#define SENSOR_DATA_TYPE_FILTERED_ACC_NED_Z					32


#define SENSOR_DATA_TYPE_CALCULATED_MADGWICK_YAW			33
#define SENSOR_DATA_TYPE_CALCULATED_MADGWICK_PITCH			34
#define SENSOR_DATA_TYPE_CALCULATED_MADGWICK_ROLL			35

#define SENSOR_DATA_TYPE_RELATIVE_POSITION_NED_Z_DIFF		36
#define SENSOR_DATA_TYPE_RELATIVE_POSITION_NED_Z_FILTERED	37

#define SENSOR_DATA_TYPE_ABSOLUTE_POSITION_NED_X	38
#define SENSOR_DATA_TYPE_ABSOLUTE_POSITION_NED_Y	39
#define SENSOR_DATA_TYPE_ABSOLUTE_POSITION_NED_Z	40

#define SENSOR_DATA_TYPE_ABSOLUTE_VELOCITY_NED_X	41
#define SENSOR_DATA_TYPE_ABSOLUTE_VELOCITY_NED_Y	42
#define SENSOR_DATA_TYPE_ABSOLUTE_VELOCITY_NED_Z	43

#define SENSOR_DATA_TYPE_TEMP_EULER_2_DIFF	44
#define SENSOR_DATA_TYPE_TEMP_EULER_3_DIFF	45
#define SENSOR_DATA_TYPE_TEMP_ACC_DOWN_DIFF	46

#define SENSOR_DATA_TYPE_TEMP_ACC_DOWN_DIFF_CROSSING	47
#define SENSOR_DATA_TYPE_BUFF_RESET_TIME				48

#define SENSOR_DATA_FILTERED_NED_ACC_DOWN_RMS				49